theme: jekyll-theme-dinky
title: Welcome to Donald's homepage!
description: Feel free to bookmark this to keep an eye on my project updates
description: My name is Donald and I put content and memes on my Instagram on @the_mclovin_donald_lincoln
